spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study/spring/jpa-02/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true  # sout 에 찍음
        format_sql: true

logging.level:
  org.hibernate.SQL: debug  # log에 찍음
  org.hibernate.type: trace
